### ISSUE TITLE
Error with loading pretrained weights

### ISSUE THREAD

**Issue by Hackerman28** [RituYadav92/Radar-RGB-Attentive-Multimodal-Object-Detection#3]
Hi. I'm very grateful for your paper on RGB+RADAR fusion for object detection and glad that you've open-sourced the model files.
I am trying to evaluate your model's pretrained weights which is obtained from [here](https://seafile.rlp.net/d/957d8819906a4d6c8d57/). I am using a conda environment created using your environment file  provided in the repository. There's been no changes done to the code otherwise aside from changing the path to nucoco.py since in the README.md it's samples/coco/nucoco.py but it's a different path in this repo. So here's the command I'm giving to evaluate your pretrained model.
`python nucoco.py evaluate --model ../../BIRANet_1024w.h5   --dataset /backup/datasets/NuScenes/Data/output_sweep_10_scenes_vis2/nucoco/`
Here's the error message  I'm getting.

Using TensorFlow backend.
Command:  evaluate
Model:  ../../BIRANet_1024w.h5
Dataset:  /backup/datasets/NuScenes/Data/output_sweep_10_scenes_vis2/nucoco/
Resolution:  1024
Logs: ../logs

Configurations:
BACKBONE                       resnet50
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                19
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LEARNING_RATE_DECAY            1e-06
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_anchor_loss': 1.0}
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
NAME                           coco
NUM_CLASSES                    7
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1500
POST_NMS_ROIS_TRAINING         3000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (16, 32, 64, 128, 256)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.9
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001
alpha                          0.1
beta                           0.2
gamma                          0.1

mode in build  inference
Loading weights  ../../BIRANet_1024w.h5
Traceback (most recent call last):
  File "nucoco.py", line 431, in <module>
    model.load_weights(model_path, by_name=True)
  File "Radar-RGB-Attentive-Multimodal-Object-Detection/Radar_RGB_Camera_Object_Detection/mrcnn/model.py", line 2342, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/home/mcw/miniconda3/envs/radar_rgb/lib/python3.7/site-packages/keras/engine/saving.py", line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #216 (named "dense_1"), weight <tf.Variable 'dense_1/kernel:0' shape=(256, 16) dtype=float32_ref> has shape (256, 16), but the saved weight has shape (2048, 128).

One thing I've noted is that the expected and actual weights shape are different by a factor of 8, but I don't know which parameter to change in mrcnn/configs.py to correctly load the pretrained weights. I'll very thankful if you could help me figure out the root of this error.

Also for my own curiosity, I had changed all the keras APIs with tf.keras.* ones with TF 2.3. But what had been previously possible in TF 1.14 was not possible with TF2. With keras inputs having shapes [None,None,3] some of the tensor shapes became None which cannot be passed as a tf tensor (hence the error passing python 'bool' as a tf tensor as seen in other issues). Do u have any idea as on how to overcome this issue in TF2? 

Thanks in advance for your help.

**Comment by Hackerman28** [comment]
Hi. After searching through github codes and issues for a day, I came across this TF2 variant of mask-rcnn [repo](https://github.com/leekunhee/Mask_RCNN). I replaced all the keras codes with the corresponding implementations from this repo and it works fine now. I evaluated your pretrained model using the new codes. It still shows the shape mismatch error but I bypassed it by using model.keras_model.load_weights(...,skip_mismatch=True). I'm getting the following coco mAP metrics on the validation set of your modified nuScenes dataset.

Command:  evaluate
Model:  ../../BIRANet_1024w.h5
Dataset:  /backup/datasets/NuScenes/Data/output_sweep_10_scenes_vis2/nucoco/
Resolution:  1024
Logs:  /backup/Radar-RGB-Attentive-Multimodal-Object-Detection/Radar_RGB_Camera_Object_Detection/logs
mode in build  inference
WARNING:tensorflow:From /home/mcw/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
Loading weights  ../../BIRANet_1024w.h5
WARNING:tensorflow:Skipping loading of weights for layer dense_1 due to mismatch in shape ((16, 256) vs (2048, 128)).
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
Running COCO evaluation on 710 images.
 WARNING:tensorflow:From /home/mcw/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py:2070: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
100%|###############################################################| 710/710 [04:10<00:00,  2.84it/s]
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.23s).
Accumulating evaluation results...
DONE (t=0.13s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.653
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.853
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.776
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.371
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.649
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.437
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.682
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.685
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.397
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.682
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742
Prediction time: 129.42409801483154. Average 0.18228746199272047/image

Even though it is getting evaluated, I still need to know why the shape mismatch occurs. Maybe that's the reason I'm not getting the same mAP as quoted in the paper.

**Comment by RituYadav92** [comment]
there should not be any shape mismatch. I'll check it when I have time. Meanwhile, can you try using optional arguments(model and resolution) mentioned in readme.

**Comment by LK3024629** [comment]
I have the same problem.

**Comment by Biubiubiu12** [comment]
I have the same problem.

**Comment by Biubiubiu12** [comment]
I encountered the same dimension mismatch problem. Can you send other pre-trained model files? thanks

**Comment by zhuyongWillem** [comment]
> Hi. After searching through github codes and issues for a day, I came across this TF2 variant of mask-rcnn [repo](https://github.com/leekunhee/Mask_RCNN). I replaced all the keras codes with the corresponding implementations from this repo and it works fine now. I evaluated your pretrained model using the new codes. It still shows the shape mismatch error but I bypassed it by using model.keras_model.load_weights(...,skip_mismatch=True). I'm getting the following coco mAP metrics on the validation set of your modified nuScenes dataset.
> 
> Command: evaluate Model: ../../BIRANet_1024w.h5 Dataset: /backup/datasets/NuScenes/Data/output_sweep_10_scenes_vis2/nucoco/ Resolution: 1024 Logs: /backup/Radar-RGB-Attentive-Multimodal-Object-Detection/Radar_RGB_Camera_Object_Detection/logs mode in build inference WARNING:tensorflow:From /home/mcw/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:574: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version. Instructions for updating: Use fn_output_signature instead Loading weights ../../BIRANet_1024w.h5 WARNING:tensorflow:Skipping loading of weights for layer dense_1 due to mismatch in shape ((16, 256) vs (2048, 128)). loading annotations into memory... Done (t=0.12s) creating index... index created! Running COCO evaluation on 710 images. WARNING:tensorflow:From /home/mcw/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py:2070: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version. Instructions for updating: This property should not be used in TensorFlow 2.0, as updates are applied automatically. 100%|###############################################################| 710/710 [04:10<00:00, 2.84it/s] Loading and preparing results... DONE (t=0.00s) creating index... index created! Running per image evaluation... Evaluate annotation type _bbox_ DONE (t=1.23s). Accumulating evaluation results... DONE (t=0.13s). Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.653 Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.853 Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.776 Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.371 Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.649 Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.437 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.682 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.685 Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.397 Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.682 Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742 Prediction time: 129.42409801483154. Average 0.18228746199272047/image
> 
> Even though it is getting evaluated, I still need to know why the shape mismatch occurs. Maybe that's the reason I'm not getting the same mAP as quoted in the paper.

Can you give us your new code?
